#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 Susi Lehtola
#
# Generate src/prime_table.inc — static const prime table for primes.c.
# Run from the repository root:
#   python3 tools/gen_prime_table.py > src/prime_table.inc

LIMIT = 20011

# Sieve of Eratosthenes
sieve = bytearray(LIMIT + 1)
sieve[0] = sieve[1] = 1
i = 2
while i * i <= LIMIT:
    if not sieve[i]:
        j = i * i
        while j <= LIMIT:
            sieve[j] = 1
            j += i
    i += 1

primes = [p for p in range(2, LIMIT + 1) if not sieve[p]]
prime_index = [-1] * (LIMIT + 1)
for idx, p in enumerate(primes):
    prime_index[p] = idx

print(f"/* Generated by tools/gen_prime_table.py — do not edit by hand.")
print(f" * PRIME_SIEVE_LIMIT = {LIMIT}, prime count = {len(primes)}. */")
print()

# g_nprimes
print(f"const int g_nprimes = {len(primes)};")
print()

# g_primes — 16 values per row
print(f"const int g_primes[MAX_PRIME_COUNT] = {{")
row = []
for i, p in enumerate(primes):
    row.append(f"{p:5d}")
    if len(row) == 16 or i == len(primes) - 1:
        suffix = "," if i < len(primes) - 1 else ""
        print("    " + ",".join(row) + suffix)
        row = []
print("};")
print()

# g_prime_index — 20 values per row
print(f"const short g_prime_index[PRIME_SIEVE_LIMIT + 1] = {{")
row = []
for i, v in enumerate(prime_index):
    row.append(f"{v:5d}")
    if len(row) == 20 or i == len(prime_index) - 1:
        suffix = "," if i < len(prime_index) - 1 else ""
        print("    " + ",".join(row) + suffix)
        row = []
print("};")
