/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright (c) 2026 Susi Lehtola */
#ifndef PRIMES_H
#define PRIMES_H

/*
 * Prime table and Legendre factorial valuation.
 *
 * The tables are precomputed static constants (generated by
 * tools/gen_prime_table.py into src/prime_table.inc).
 *
 * Hard correctness limit
 * ----------------------
 * pfrac_mul_factorial(n) is correct only when every prime p <= n is in the
 * table, i.e. p <= PRIME_SIEVE_LIMIT.  The first prime above PRIME_SIEVE_LIMIT
 * is 20021, so the function is correct for n <= 20020.  MAX_FACTORIAL_ARG is
 * set conservatively to 20000 to give a round-number safety margin.
 *
 * Callers must never pass a factorial argument exceeding MAX_FACTORIAL_ARG.
 * Violations produce silently wrong results (no assert, no error return).
 *
 * Angular momentum limits implied by MAX_FACTORIAL_ARG
 * -----------------------------------------------------
 * The largest factorial argument in each symbol comes from the triangle-
 * coefficient denominator (j1+j2+j3+1)!, so:
 *
 *   3j, 6j, CG, Racah W, Gaunt:
 *     j1+j2+j3 <= 19999  (equal-j: j <= 6666)
 *
 *   9j (via wigner9j_exact):
 *     The k-dependent Delta denominators reach (4j+1)! for equal j, so
 *     j <= 4999 when all nine angular momenta are equal.
 *
 * Performance note
 * ----------------
 * The Racah sum has O(j) terms for 3j/6j and O(j^2) total for 9j (outer k
 * loop times inner Racah sums).  Intermediate bigints grow as ~j/ln2 bits.
 * Practical performance horizons (order of magnitude, modern hardware):
 *
 *   3j / 6j  :  j ~ 1000  in milliseconds;  j ~ 6000  in seconds
 *   9j       :  j ~  100  in milliseconds;  j ~ 1000  in minutes
 */

#define PRIME_SIEVE_LIMIT   20011   /* sieve all primes up to this value    */
#define MAX_PRIME_COUNT     2263    /* pi(20011) = 2263                     */
#define MAX_FACTORIAL_ARG   20000   /* hard limit: see note above           */

/* Number of primes in the table. */
extern const int g_nprimes;

/* g_primes[i] = i-th prime (0-indexed: g_primes[0]=2, g_primes[1]=3, ...) */
extern const int g_primes[MAX_PRIME_COUNT];

/*
 * g_prime_index[p] = index i such that g_primes[i] == p, or -1.
 * Valid for 0 <= p <= PRIME_SIEVE_LIMIT.
 */
extern const short g_prime_index[PRIME_SIEVE_LIMIT + 1];

/*
 * Return v_p(n!) = sum_{k>=1} floor(n / p^k), the p-adic valuation of n!.
 * pi is the index of p in g_primes.  n must satisfy 0 <= n <= MAX_FACTORIAL_ARG.
 */
int legendre_valuation(int n, int pi);

#endif /* PRIMES_H */
